spring.application.name=Idopontfoglalo
#h2
spring.datasource.url=jdbc:h2:file:./data/idopontdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=titok123

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.security.user.name=admin
spring.security.user.password=titok123
spring.security.user.roles=ADMIN

server.servlet.session.timeout=10m

# Email configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=830e4d1726465a
spring.mail.password=96e2223985164f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

app.email.from=noreply@idopontfoglalo.hu

#IIS
server.port=8080
server.forward-headers-strategy=framework

server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
